var adatok=[
    {
        "Vármegye": "",
        "Székhely": "",
        "Országrész": "",
        "Régió": "",
        "Járás": "",
        "Település": "össz.",
        "": "város",
        "Népesség": "",
        "Terület": "",
        "Nép-": "sűrűség"
    },
    {
        "Vármegye": "Bács-Kiskun",
        "Székhely": "Kecskemét",
        "Országrész": "AF",
        "Régió": "DA",
        "Járás": "11",
        "Település": "119",
        "": "22",
        "Népesség": "503 825",
        "Terület": "8 443",
        "Nép-": "59"
    },
    {
        "Vármegye": "Baranya",
        "Székhely": "Pécs",
        "Országrész": "DT",
        "Régió": "DD",
        "Járás": "10",
        "Település": "301",
        "": "14",
        "Népesség": "360 704",
        "Terület": "4 430",
        "Nép-": "81"
    },
    {
        "Vármegye": "Békés",
        "Székhely": "Békéscsaba",
        "Országrész": "AF",
        "Régió": "DA",
        "Járás": "9",
        "Település": "75",
        "": "22",
        "Népesség": "334 264",
        "Terület": "5 630",
        "Nép-": "59"
    },
    {
        "Vármegye": "Borsod-Abaúj-Zemplén",
        "Székhely": "Miskolc",
        "Országrész": "AF",
        "Régió": "ÉM",
        "Járás": "16",
        "Település": "358",
        "": "29",
        "Népesség": "642 447",
        "Terület": "7 247",
        "Nép-": "88"
    },
    {
        "Vármegye": "Csongrád-Csanád",
        "Székhely": "Szeged",
        "Országrész": "AF",
        "Régió": "DA",
        "Járás": "7",
        "Település": "60",
        "": "10",
        "Népesség": "399 012",
        "Terület": "4 262",
        "Nép-": "93"
    },
    {
        "Vármegye": "Fejér",
        "Székhely": "Székesfehérvár",
        "Országrész": "DT",
        "Régió": "KD",
        "Járás": "8",
        "Település": "108",
        "": "17",
        "Népesség": "417 712",
        "Terület": "4 358",
        "Nép-": "95"
    },
    {
        "Vármegye": "Győr-Moson-Sopron",
        "Székhely": "Győr",
        "Országrész": "DT",
        "Régió": "NyD",
        "Járás": "7",
        "Település": "183",
        "": "12",
        "Népesség": "467 144",
        "Terület": "4 208",
        "Nép-": "111"
    },
    {
        "Vármegye": "Hajdú-Bihar",
        "Székhely": "Debrecen",
        "Országrész": "AF",
        "Régió": "ÉA",
        "Járás": "10",
        "Település": "82",
        "": "21",
        "Népesség": "527 989",
        "Terület": "6 209",
        "Nép-": "85"
    },
    {
        "Vármegye": "Heves",
        "Székhely": "Eger",
        "Országrész": "AF",
        "Régió": "ÉM",
        "Járás": "7",
        "Település": "121",
        "": "11",
        "Népesség": "294 609",
        "Terület": "3 637",
        "Nép-": "81"
    },
    {
        "Vármegye": "Jász-Nagykun-Szolnok",
        "Székhely": "Szolnok",
        "Országrész": "AF",
        "Régió": "ÉA",
        "Járás": "9",
        "Település": "78",
        "": "22",
        "Népesség": "370 007",
        "Terület": "5 581",
        "Nép-": "66"
    },
    {
        "Vármegye": "Komárom-Esztergom",
        "Székhely": "Tatabánya",
        "Országrész": "DT",
        "Régió": "KD",
        "Járás": "6",
        "Település": "76",
        "": "12",
        "Népesség": "299 207",
        "Terület": "2 264",
        "Nép-": "132"
    },
    {
        "Vármegye": "Nógrád",
        "Székhely": "Salgótarján",
        "Országrész": "AF",
        "Régió": "ÉM",
        "Járás": "6",
        "Település": "131",
        "": "6",
        "Népesség": "189 304",
        "Terület": "2 544",
        "Nép-": "74"
    },
    {
        "Vármegye": "Pest",
        "Székhely": "Budapest",
        "Országrész": "KM",
        "Régió": "PE",
        "Járás": "18",
        "Település": "187",
        "": "52",
        "Népesség": "1 278 874",
        "Terület": "6 390",
        "Nép-": "200"
    },
    {
        "Vármegye": "Somogy",
        "Székhely": "Kaposvár",
        "Országrész": "DT",
        "Régió": "DD",
        "Járás": "8",
        "Település": "246",
        "": "16",
        "Népesség": "301 429",
        "Terület": "6 065",
        "Nép-": "49"
    },
    {
        "Vármegye": "Szabolcs-Szatmár-Bereg",
        "Székhely": "Nyíregyháza",
        "Országrész": "AF",
        "Régió": "ÉA",
        "Járás": "13",
        "Település": "229",
        "": "29",
        "Népesség": "552 964",
        "Terület": "5 933",
        "Nép-": "93"
    },
    {
        "Vármegye": "Tolna",
        "Székhely": "Szekszárd",
        "Országrész": "DT",
        "Régió": "DD",
        "Járás": "6",
        "Település": "109",
        "": "11",
        "Népesség": "217 463",
        "Terület": "3 703",
        "Nép-": "58"
    },
    {
        "Vármegye": "Vas",
        "Székhely": "Szombathely",
        "Országrész": "DT",
        "Régió": "NyD",
        "Járás": "7",
        "Település": "216",
        "": "13",
        "Népesség": "253 551",
        "Terület": "3 336",
        "Nép-": "76"
    },
    {
        "Vármegye": "Veszprém",
        "Székhely": "Veszprém",
        "Országrész": "DT",
        "Régió": "KD",
        "Járás": "10",
        "Település": "217",
        "": "15",
        "Népesség": "341 317",
        "Terület": "4 463",
        "Nép-": "76"
    },
    {
        "Vármegye": "Zala",
        "Székhely": "Zalaegerszeg",
        "Országrész": "DT",
        "Régió": "NyD",
        "Járás": "6",
        "Település": "258",
        "": "10",
        "Népesség": "268 648",
        "Terület": "3 784",
        "Nép-": "71"
    },
    {
        "Vármegye": "Budapest (főváros)",
        "Székhely": "–",
        "Országrész": "KM",
        "Régió": "BU",
        "Járás": "23",
        "Település": "23",
        "": "–",
        "Népesség": "1 752 286",
        "Terület": "525",
        "Nép-": "3 337"
    }
]